services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - ./src:/var/www
        networks:
            - laravel-network
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=moview_db
            - DB_USERNAME=postgres
            - DB_PASSWORD=secret
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: laravel-db
        environment:
            - POSTGRES_DB=moview_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    postgres_data:
