services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - ./src:/var/www
        networks:
            - laravel-network
        environment:
            - DB_HOST=postgres-ifxh.railway.internal
            - DB_PORT=5432
            - DB_DATABASE=railway
            - DB_USERNAME=postgres
            - DB_PASSWORD=yVfaFYoGjHLzbJQgkdRYFwpUQqmizqhO
        depends_on:
            db:
                condition: service_healthy

    db:
        image: agim221/webdev:db
        container_name: laravel-db
        environment:
            - POSTGRES_DB=moview_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    frontend:
        image: agim221/webdev:frontend
        container_name: laravel-frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/var/www
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    postgres_data:
